### PR TITLE
Updated buildkit, starter site, demo objects, workbench, and solr config

### PR DESCRIPTION
**Pull request by ajstanley**
Updates everything in the build to current releases.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Also noticed rights field is being rendered as plain text rather than HTML.

Screenshot 2024-02-19 at 21 20 52

**Comment by nigelgbanks** [comment]
Everything else I checked seemed to work well.

**Comment by ajstanley** [comment]
Weird - it looks like you still have the old Solr config and the old template file for the workbench config file.  
Did you re-run the build command?

**Comment by nigelgbanks** [comment]
I did rerun the build command, it seems like there was some caching issue though. I wiped my docker build cache and then it worked as intended!

**Comment by ajstanley** [comment]
Thanks @nigelgbanks !

**Pull request merged**
