### PR TITLE
Update to use new starter site

### PR DESCRIPTION
**Pull request by rosiel**
Updates the hashes and commits of Workbench, Demo Objects, and Starter Site.

### CODE REVIEW

**Comment by rosiel** [comment]
@nigelgbanks I think the build will fail because of Drush Launcher and Drush 12. That's what seemed to happen on my machine (the drupal container balked and exited). I put it here hoping more eyeballs would see it but it seems that PRs don't trigger a build anymore.

**Comment by nigelgbanks** [comment]
I tried locally, and made a few changes to your pull.

Mainly, I changed the source images for `isle-buildkit` to use the latest release.

```bash
ISLANDORA_TAG=2.0.10
```

And a change to `default_settings.txt` to account for the changes to the Drupal API.

Followed by:

```bash
docker compose build
docker compose pull 
```

Seems to work.

**Comment by rosiel** [comment]
With your fixes, it runs! 🥳 

I encountered an error w.r.t. IIIF manifest generation that Born Digital has a fix for (thank you!) and I think it'll be worth waiting till the books display in Mirador properly before launching this. Thus, I'm keeping it in draft for now.

**Comment by ajstanley** [comment]
I saw a few conflicts with the IIIF module.  Excerpt from 'Wild flowers of Western Canada' shows JSON errors. This comes from a logic issue which has been fixed (Issue 1000)  in `main`, but not the latest tag. 
If we fix that one we get Cantaloupe errors that come from a bad config file. If we set `processor.selection_strategy = ManualSelectionStrategy` and `processor.ManualSelectionStrategy.jp2 = OpenJpegProcessor` we get good results.
This was fixed 2 months ago, but still not in a tagged release.

**Comment by ajstanley** [comment]
I bumped the version to 3.0.7.  Mirador books now display properly.
I'll put in a separate ticket to update composer.json, composer.lock and core.ext in config on Starter Site, but this runs well for now.

**Comment by nigelgbanks** [comment]
Tested locally and this looks to work well.

**Pull request merged**
